/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NavbarLayoutRouteImport } from './routes/_navbar-layout'
import { Route as NavbarLayoutIndexRouteImport } from './routes/_navbar-layout.index'
import { Route as WatchInviteCodeRouteImport } from './routes/watch.$inviteCode'
import { Route as GGameInstanceIdRouteImport } from './routes/g.$gameInstanceId'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as NavbarLayoutAuthRouteImport } from './routes/_navbar-layout._auth'
import { Route as NavbarLayoutAuthStartRouteImport } from './routes/_navbar-layout._auth.start'
import { Route as NavbarLayoutAuthQuestionsRouteImport } from './routes/_navbar-layout._auth.questions'
import { Route as NavbarLayoutAuthGamesRouteImport } from './routes/_navbar-layout._auth.games'
import { Route as AuthCGameInstanceIdRouteImport } from './routes/_auth.c.$gameInstanceId'
import { Route as NavbarLayoutAuthGamesIndexRouteImport } from './routes/_navbar-layout._auth.games.index'
import { Route as AuthCGameInstanceIdIndexRouteImport } from './routes/_auth.c.$gameInstanceId.index'
import { Route as NavbarLayoutAuthGamesGameIdRouteImport } from './routes/_navbar-layout._auth.games.$gameId'
import { Route as AuthCGameInstanceIdQuestionIdRouteImport } from './routes/_auth.c.$gameInstanceId.$questionId'

const AboutLazyRouteImport = createFileRoute('/about')()

const AboutLazyRoute = AboutLazyRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NavbarLayoutRoute = NavbarLayoutRouteImport.update({
  id: '/_navbar-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const NavbarLayoutIndexRoute = NavbarLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NavbarLayoutRoute,
} as any)
const WatchInviteCodeRoute = WatchInviteCodeRouteImport.update({
  id: '/watch/$inviteCode',
  path: '/watch/$inviteCode',
  getParentRoute: () => rootRouteImport,
} as any)
const GGameInstanceIdRoute = GGameInstanceIdRouteImport.update({
  id: '/g/$gameInstanceId',
  path: '/g/$gameInstanceId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const NavbarLayoutAuthRoute = NavbarLayoutAuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => NavbarLayoutRoute,
} as any)
const NavbarLayoutAuthStartRoute = NavbarLayoutAuthStartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => NavbarLayoutAuthRoute,
} as any)
const NavbarLayoutAuthQuestionsRoute =
  NavbarLayoutAuthQuestionsRouteImport.update({
    id: '/questions',
    path: '/questions',
    getParentRoute: () => NavbarLayoutAuthRoute,
  } as any)
const NavbarLayoutAuthGamesRoute = NavbarLayoutAuthGamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => NavbarLayoutAuthRoute,
} as any)
const AuthCGameInstanceIdRoute = AuthCGameInstanceIdRouteImport.update({
  id: '/_auth/c/$gameInstanceId',
  path: '/c/$gameInstanceId',
  getParentRoute: () => rootRouteImport,
} as any)
const NavbarLayoutAuthGamesIndexRoute =
  NavbarLayoutAuthGamesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => NavbarLayoutAuthGamesRoute,
  } as any)
const AuthCGameInstanceIdIndexRoute =
  AuthCGameInstanceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthCGameInstanceIdRoute,
  } as any)
const NavbarLayoutAuthGamesGameIdRoute =
  NavbarLayoutAuthGamesGameIdRouteImport.update({
    id: '/$gameId',
    path: '/$gameId',
    getParentRoute: () => NavbarLayoutAuthGamesRoute,
  } as any)
const AuthCGameInstanceIdQuestionIdRoute =
  AuthCGameInstanceIdQuestionIdRouteImport.update({
    id: '/$questionId',
    path: '/$questionId',
    getParentRoute: () => AuthCGameInstanceIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof NavbarLayoutIndexRoute
  '/login': typeof LoginRoute
  '/about': typeof AboutLazyRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/g/$gameInstanceId': typeof GGameInstanceIdRoute
  '/watch/$inviteCode': typeof WatchInviteCodeRoute
  '/c/$gameInstanceId': typeof AuthCGameInstanceIdRouteWithChildren
  '/games': typeof NavbarLayoutAuthGamesRouteWithChildren
  '/questions': typeof NavbarLayoutAuthQuestionsRoute
  '/start': typeof NavbarLayoutAuthStartRoute
  '/c/$gameInstanceId/$questionId': typeof AuthCGameInstanceIdQuestionIdRoute
  '/games/$gameId': typeof NavbarLayoutAuthGamesGameIdRoute
  '/c/$gameInstanceId/': typeof AuthCGameInstanceIdIndexRoute
  '/games/': typeof NavbarLayoutAuthGamesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/about': typeof AboutLazyRoute
  '/': typeof NavbarLayoutIndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/g/$gameInstanceId': typeof GGameInstanceIdRoute
  '/watch/$inviteCode': typeof WatchInviteCodeRoute
  '/questions': typeof NavbarLayoutAuthQuestionsRoute
  '/start': typeof NavbarLayoutAuthStartRoute
  '/c/$gameInstanceId/$questionId': typeof AuthCGameInstanceIdQuestionIdRoute
  '/games/$gameId': typeof NavbarLayoutAuthGamesGameIdRoute
  '/c/$gameInstanceId': typeof AuthCGameInstanceIdIndexRoute
  '/games': typeof NavbarLayoutAuthGamesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_navbar-layout': typeof NavbarLayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/about': typeof AboutLazyRoute
  '/_navbar-layout/_auth': typeof NavbarLayoutAuthRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/g/$gameInstanceId': typeof GGameInstanceIdRoute
  '/watch/$inviteCode': typeof WatchInviteCodeRoute
  '/_navbar-layout/': typeof NavbarLayoutIndexRoute
  '/_auth/c/$gameInstanceId': typeof AuthCGameInstanceIdRouteWithChildren
  '/_navbar-layout/_auth/games': typeof NavbarLayoutAuthGamesRouteWithChildren
  '/_navbar-layout/_auth/questions': typeof NavbarLayoutAuthQuestionsRoute
  '/_navbar-layout/_auth/start': typeof NavbarLayoutAuthStartRoute
  '/_auth/c/$gameInstanceId/$questionId': typeof AuthCGameInstanceIdQuestionIdRoute
  '/_navbar-layout/_auth/games/$gameId': typeof NavbarLayoutAuthGamesGameIdRoute
  '/_auth/c/$gameInstanceId/': typeof AuthCGameInstanceIdIndexRoute
  '/_navbar-layout/_auth/games/': typeof NavbarLayoutAuthGamesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/about'
    | '/auth/callback'
    | '/g/$gameInstanceId'
    | '/watch/$inviteCode'
    | '/c/$gameInstanceId'
    | '/games'
    | '/questions'
    | '/start'
    | '/c/$gameInstanceId/$questionId'
    | '/games/$gameId'
    | '/c/$gameInstanceId/'
    | '/games/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/about'
    | '/'
    | '/auth/callback'
    | '/g/$gameInstanceId'
    | '/watch/$inviteCode'
    | '/questions'
    | '/start'
    | '/c/$gameInstanceId/$questionId'
    | '/games/$gameId'
    | '/c/$gameInstanceId'
    | '/games'
  id:
    | '__root__'
    | '/_navbar-layout'
    | '/login'
    | '/about'
    | '/_navbar-layout/_auth'
    | '/auth/callback'
    | '/g/$gameInstanceId'
    | '/watch/$inviteCode'
    | '/_navbar-layout/'
    | '/_auth/c/$gameInstanceId'
    | '/_navbar-layout/_auth/games'
    | '/_navbar-layout/_auth/questions'
    | '/_navbar-layout/_auth/start'
    | '/_auth/c/$gameInstanceId/$questionId'
    | '/_navbar-layout/_auth/games/$gameId'
    | '/_auth/c/$gameInstanceId/'
    | '/_navbar-layout/_auth/games/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  NavbarLayoutRoute: typeof NavbarLayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  AboutLazyRoute: typeof AboutLazyRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  GGameInstanceIdRoute: typeof GGameInstanceIdRoute
  WatchInviteCodeRoute: typeof WatchInviteCodeRoute
  AuthCGameInstanceIdRoute: typeof AuthCGameInstanceIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_navbar-layout': {
      id: '/_navbar-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof NavbarLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_navbar-layout/': {
      id: '/_navbar-layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof NavbarLayoutIndexRouteImport
      parentRoute: typeof NavbarLayoutRoute
    }
    '/watch/$inviteCode': {
      id: '/watch/$inviteCode'
      path: '/watch/$inviteCode'
      fullPath: '/watch/$inviteCode'
      preLoaderRoute: typeof WatchInviteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g/$gameInstanceId': {
      id: '/g/$gameInstanceId'
      path: '/g/$gameInstanceId'
      fullPath: '/g/$gameInstanceId'
      preLoaderRoute: typeof GGameInstanceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_navbar-layout/_auth': {
      id: '/_navbar-layout/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof NavbarLayoutAuthRouteImport
      parentRoute: typeof NavbarLayoutRoute
    }
    '/_navbar-layout/_auth/start': {
      id: '/_navbar-layout/_auth/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof NavbarLayoutAuthStartRouteImport
      parentRoute: typeof NavbarLayoutAuthRoute
    }
    '/_navbar-layout/_auth/questions': {
      id: '/_navbar-layout/_auth/questions'
      path: '/questions'
      fullPath: '/questions'
      preLoaderRoute: typeof NavbarLayoutAuthQuestionsRouteImport
      parentRoute: typeof NavbarLayoutAuthRoute
    }
    '/_navbar-layout/_auth/games': {
      id: '/_navbar-layout/_auth/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof NavbarLayoutAuthGamesRouteImport
      parentRoute: typeof NavbarLayoutAuthRoute
    }
    '/_auth/c/$gameInstanceId': {
      id: '/_auth/c/$gameInstanceId'
      path: '/c/$gameInstanceId'
      fullPath: '/c/$gameInstanceId'
      preLoaderRoute: typeof AuthCGameInstanceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_navbar-layout/_auth/games/': {
      id: '/_navbar-layout/_auth/games/'
      path: '/'
      fullPath: '/games/'
      preLoaderRoute: typeof NavbarLayoutAuthGamesIndexRouteImport
      parentRoute: typeof NavbarLayoutAuthGamesRoute
    }
    '/_auth/c/$gameInstanceId/': {
      id: '/_auth/c/$gameInstanceId/'
      path: '/'
      fullPath: '/c/$gameInstanceId/'
      preLoaderRoute: typeof AuthCGameInstanceIdIndexRouteImport
      parentRoute: typeof AuthCGameInstanceIdRoute
    }
    '/_navbar-layout/_auth/games/$gameId': {
      id: '/_navbar-layout/_auth/games/$gameId'
      path: '/$gameId'
      fullPath: '/games/$gameId'
      preLoaderRoute: typeof NavbarLayoutAuthGamesGameIdRouteImport
      parentRoute: typeof NavbarLayoutAuthGamesRoute
    }
    '/_auth/c/$gameInstanceId/$questionId': {
      id: '/_auth/c/$gameInstanceId/$questionId'
      path: '/$questionId'
      fullPath: '/c/$gameInstanceId/$questionId'
      preLoaderRoute: typeof AuthCGameInstanceIdQuestionIdRouteImport
      parentRoute: typeof AuthCGameInstanceIdRoute
    }
  }
}

interface NavbarLayoutAuthGamesRouteChildren {
  NavbarLayoutAuthGamesGameIdRoute: typeof NavbarLayoutAuthGamesGameIdRoute
  NavbarLayoutAuthGamesIndexRoute: typeof NavbarLayoutAuthGamesIndexRoute
}

const NavbarLayoutAuthGamesRouteChildren: NavbarLayoutAuthGamesRouteChildren = {
  NavbarLayoutAuthGamesGameIdRoute: NavbarLayoutAuthGamesGameIdRoute,
  NavbarLayoutAuthGamesIndexRoute: NavbarLayoutAuthGamesIndexRoute,
}

const NavbarLayoutAuthGamesRouteWithChildren =
  NavbarLayoutAuthGamesRoute._addFileChildren(
    NavbarLayoutAuthGamesRouteChildren,
  )

interface NavbarLayoutAuthRouteChildren {
  NavbarLayoutAuthGamesRoute: typeof NavbarLayoutAuthGamesRouteWithChildren
  NavbarLayoutAuthQuestionsRoute: typeof NavbarLayoutAuthQuestionsRoute
  NavbarLayoutAuthStartRoute: typeof NavbarLayoutAuthStartRoute
}

const NavbarLayoutAuthRouteChildren: NavbarLayoutAuthRouteChildren = {
  NavbarLayoutAuthGamesRoute: NavbarLayoutAuthGamesRouteWithChildren,
  NavbarLayoutAuthQuestionsRoute: NavbarLayoutAuthQuestionsRoute,
  NavbarLayoutAuthStartRoute: NavbarLayoutAuthStartRoute,
}

const NavbarLayoutAuthRouteWithChildren =
  NavbarLayoutAuthRoute._addFileChildren(NavbarLayoutAuthRouteChildren)

interface NavbarLayoutRouteChildren {
  NavbarLayoutAuthRoute: typeof NavbarLayoutAuthRouteWithChildren
  NavbarLayoutIndexRoute: typeof NavbarLayoutIndexRoute
}

const NavbarLayoutRouteChildren: NavbarLayoutRouteChildren = {
  NavbarLayoutAuthRoute: NavbarLayoutAuthRouteWithChildren,
  NavbarLayoutIndexRoute: NavbarLayoutIndexRoute,
}

const NavbarLayoutRouteWithChildren = NavbarLayoutRoute._addFileChildren(
  NavbarLayoutRouteChildren,
)

interface AuthCGameInstanceIdRouteChildren {
  AuthCGameInstanceIdQuestionIdRoute: typeof AuthCGameInstanceIdQuestionIdRoute
  AuthCGameInstanceIdIndexRoute: typeof AuthCGameInstanceIdIndexRoute
}

const AuthCGameInstanceIdRouteChildren: AuthCGameInstanceIdRouteChildren = {
  AuthCGameInstanceIdQuestionIdRoute: AuthCGameInstanceIdQuestionIdRoute,
  AuthCGameInstanceIdIndexRoute: AuthCGameInstanceIdIndexRoute,
}

const AuthCGameInstanceIdRouteWithChildren =
  AuthCGameInstanceIdRoute._addFileChildren(AuthCGameInstanceIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  NavbarLayoutRoute: NavbarLayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  AboutLazyRoute: AboutLazyRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  GGameInstanceIdRoute: GGameInstanceIdRoute,
  WatchInviteCodeRoute: WatchInviteCodeRoute,
  AuthCGameInstanceIdRoute: AuthCGameInstanceIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
