/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as NavbarLayoutImport } from './routes/_navbar-layout'
import { Route as NavbarLayoutIndexImport } from './routes/_navbar-layout.index'
import { Route as GGameInstanceIdImport } from './routes/g.$gameInstanceId'
import { Route as NavbarLayoutLoginImport } from './routes/_navbar-layout.login'
import { Route as NavbarLayoutActiveImport } from './routes/_navbar-layout.active'
import { Route as NavbarLayoutAuthImport } from './routes/_navbar-layout._auth'
import { Route as NavbarLayoutauthCImport } from './routes/_navbar-layout_._auth.c'
import { Route as NavbarLayoutAuthEImport } from './routes/_navbar-layout._auth.e'
import { Route as NavbarLayoutauthCIndexImport } from './routes/_navbar-layout_._auth.c.index'
import { Route as NavbarLayoutAuthEIndexImport } from './routes/_navbar-layout._auth.e.index'
import { Route as NavbarLayoutauthCGameInstanceIdImport } from './routes/_navbar-layout_._auth.c.$gameInstanceId'
import { Route as NavbarLayoutAuthEQuestionsImport } from './routes/_navbar-layout._auth.e.questions'
import { Route as NavbarLayoutAuthEGamesImport } from './routes/_navbar-layout._auth.e.games'
import { Route as NavbarLayoutAuthEQuestionsIndexImport } from './routes/_navbar-layout._auth.e.questions.index'
import { Route as NavbarLayoutAuthEGamesIndexImport } from './routes/_navbar-layout._auth.e.games.index'
import { Route as NavbarLayoutAuthEQuestionsQuestionIdImport } from './routes/_navbar-layout._auth.e.questions.$questionId'
import { Route as NavbarLayoutAuthEGamesGameIdImport } from './routes/_navbar-layout._auth.e.games.$gameId'

// Create Virtual Routes

const AboutLazyImport = createFileRoute('/about')()

// Create/Update Routes

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const NavbarLayoutRoute = NavbarLayoutImport.update({
  id: '/_navbar-layout',
  getParentRoute: () => rootRoute,
} as any)

const NavbarLayoutIndexRoute = NavbarLayoutIndexImport.update({
  path: '/',
  getParentRoute: () => NavbarLayoutRoute,
} as any)

const GGameInstanceIdRoute = GGameInstanceIdImport.update({
  path: '/g/$gameInstanceId',
  getParentRoute: () => rootRoute,
} as any)

const NavbarLayoutLoginRoute = NavbarLayoutLoginImport.update({
  path: '/login',
  getParentRoute: () => NavbarLayoutRoute,
} as any)

const NavbarLayoutActiveRoute = NavbarLayoutActiveImport.update({
  path: '/active',
  getParentRoute: () => NavbarLayoutRoute,
} as any)

const NavbarLayoutAuthRoute = NavbarLayoutAuthImport.update({
  id: '/_auth',
  getParentRoute: () => NavbarLayoutRoute,
} as any)

const NavbarLayoutauthCRoute = NavbarLayoutauthCImport.update({
  path: '/c',
  getParentRoute: () => rootRoute,
} as any)

const NavbarLayoutAuthERoute = NavbarLayoutAuthEImport.update({
  path: '/e',
  getParentRoute: () => NavbarLayoutAuthRoute,
} as any)

const NavbarLayoutauthCIndexRoute = NavbarLayoutauthCIndexImport.update({
  path: '/',
  getParentRoute: () => NavbarLayoutauthCRoute,
} as any)

const NavbarLayoutAuthEIndexRoute = NavbarLayoutAuthEIndexImport.update({
  path: '/',
  getParentRoute: () => NavbarLayoutAuthERoute,
} as any)

const NavbarLayoutauthCGameInstanceIdRoute =
  NavbarLayoutauthCGameInstanceIdImport.update({
    path: '/$gameInstanceId',
    getParentRoute: () => NavbarLayoutauthCRoute,
  } as any)

const NavbarLayoutAuthEQuestionsRoute = NavbarLayoutAuthEQuestionsImport.update(
  {
    path: '/questions',
    getParentRoute: () => NavbarLayoutAuthERoute,
  } as any,
)

const NavbarLayoutAuthEGamesRoute = NavbarLayoutAuthEGamesImport.update({
  path: '/games',
  getParentRoute: () => NavbarLayoutAuthERoute,
} as any)

const NavbarLayoutAuthEQuestionsIndexRoute =
  NavbarLayoutAuthEQuestionsIndexImport.update({
    path: '/',
    getParentRoute: () => NavbarLayoutAuthEQuestionsRoute,
  } as any)

const NavbarLayoutAuthEGamesIndexRoute =
  NavbarLayoutAuthEGamesIndexImport.update({
    path: '/',
    getParentRoute: () => NavbarLayoutAuthEGamesRoute,
  } as any)

const NavbarLayoutAuthEQuestionsQuestionIdRoute =
  NavbarLayoutAuthEQuestionsQuestionIdImport.update({
    path: '/$questionId',
    getParentRoute: () => NavbarLayoutAuthEQuestionsRoute,
  } as any)

const NavbarLayoutAuthEGamesGameIdRoute =
  NavbarLayoutAuthEGamesGameIdImport.update({
    path: '/$gameId',
    getParentRoute: () => NavbarLayoutAuthEGamesRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_navbar-layout': {
      id: '/_navbar-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof NavbarLayoutImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/_navbar-layout/_auth': {
      id: '/_navbar-layout/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof NavbarLayoutAuthImport
      parentRoute: typeof NavbarLayoutImport
    }
    '/_navbar-layout/active': {
      id: '/_navbar-layout/active'
      path: '/active'
      fullPath: '/active'
      preLoaderRoute: typeof NavbarLayoutActiveImport
      parentRoute: typeof NavbarLayoutImport
    }
    '/_navbar-layout/login': {
      id: '/_navbar-layout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof NavbarLayoutLoginImport
      parentRoute: typeof NavbarLayoutImport
    }
    '/g/$gameInstanceId': {
      id: '/g/$gameInstanceId'
      path: '/g/$gameInstanceId'
      fullPath: '/g/$gameInstanceId'
      preLoaderRoute: typeof GGameInstanceIdImport
      parentRoute: typeof rootRoute
    }
    '/_navbar-layout/': {
      id: '/_navbar-layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof NavbarLayoutIndexImport
      parentRoute: typeof NavbarLayoutImport
    }
    '/_navbar-layout/_auth/e': {
      id: '/_navbar-layout/_auth/e'
      path: '/e'
      fullPath: '/e'
      preLoaderRoute: typeof NavbarLayoutAuthEImport
      parentRoute: typeof NavbarLayoutAuthImport
    }
    '/_navbar-layout/_auth/c': {
      id: '/_navbar-layout/_auth/c'
      path: '/c'
      fullPath: '/c'
      preLoaderRoute: typeof NavbarLayoutauthCImport
      parentRoute: typeof rootRoute
    }
    '/_navbar-layout/_auth/e/games': {
      id: '/_navbar-layout/_auth/e/games'
      path: '/games'
      fullPath: '/e/games'
      preLoaderRoute: typeof NavbarLayoutAuthEGamesImport
      parentRoute: typeof NavbarLayoutAuthEImport
    }
    '/_navbar-layout/_auth/e/questions': {
      id: '/_navbar-layout/_auth/e/questions'
      path: '/questions'
      fullPath: '/e/questions'
      preLoaderRoute: typeof NavbarLayoutAuthEQuestionsImport
      parentRoute: typeof NavbarLayoutAuthEImport
    }
    '/_navbar-layout/_auth/c/$gameInstanceId': {
      id: '/_navbar-layout/_auth/c/$gameInstanceId'
      path: '/$gameInstanceId'
      fullPath: '/c/$gameInstanceId'
      preLoaderRoute: typeof NavbarLayoutauthCGameInstanceIdImport
      parentRoute: typeof NavbarLayoutauthCImport
    }
    '/_navbar-layout/_auth/e/': {
      id: '/_navbar-layout/_auth/e/'
      path: '/'
      fullPath: '/e/'
      preLoaderRoute: typeof NavbarLayoutAuthEIndexImport
      parentRoute: typeof NavbarLayoutAuthEImport
    }
    '/_navbar-layout/_auth/c/': {
      id: '/_navbar-layout/_auth/c/'
      path: '/'
      fullPath: '/c/'
      preLoaderRoute: typeof NavbarLayoutauthCIndexImport
      parentRoute: typeof NavbarLayoutauthCImport
    }
    '/_navbar-layout/_auth/e/games/$gameId': {
      id: '/_navbar-layout/_auth/e/games/$gameId'
      path: '/$gameId'
      fullPath: '/e/games/$gameId'
      preLoaderRoute: typeof NavbarLayoutAuthEGamesGameIdImport
      parentRoute: typeof NavbarLayoutAuthEGamesImport
    }
    '/_navbar-layout/_auth/e/questions/$questionId': {
      id: '/_navbar-layout/_auth/e/questions/$questionId'
      path: '/$questionId'
      fullPath: '/e/questions/$questionId'
      preLoaderRoute: typeof NavbarLayoutAuthEQuestionsQuestionIdImport
      parentRoute: typeof NavbarLayoutAuthEQuestionsImport
    }
    '/_navbar-layout/_auth/e/games/': {
      id: '/_navbar-layout/_auth/e/games/'
      path: '/'
      fullPath: '/e/games/'
      preLoaderRoute: typeof NavbarLayoutAuthEGamesIndexImport
      parentRoute: typeof NavbarLayoutAuthEGamesImport
    }
    '/_navbar-layout/_auth/e/questions/': {
      id: '/_navbar-layout/_auth/e/questions/'
      path: '/'
      fullPath: '/e/questions/'
      preLoaderRoute: typeof NavbarLayoutAuthEQuestionsIndexImport
      parentRoute: typeof NavbarLayoutAuthEQuestionsImport
    }
  }
}

// Create and export the route tree

interface NavbarLayoutAuthEGamesRouteChildren {
  NavbarLayoutAuthEGamesGameIdRoute: typeof NavbarLayoutAuthEGamesGameIdRoute
  NavbarLayoutAuthEGamesIndexRoute: typeof NavbarLayoutAuthEGamesIndexRoute
}

const NavbarLayoutAuthEGamesRouteChildren: NavbarLayoutAuthEGamesRouteChildren =
  {
    NavbarLayoutAuthEGamesGameIdRoute: NavbarLayoutAuthEGamesGameIdRoute,
    NavbarLayoutAuthEGamesIndexRoute: NavbarLayoutAuthEGamesIndexRoute,
  }

const NavbarLayoutAuthEGamesRouteWithChildren =
  NavbarLayoutAuthEGamesRoute._addFileChildren(
    NavbarLayoutAuthEGamesRouteChildren,
  )

interface NavbarLayoutAuthEQuestionsRouteChildren {
  NavbarLayoutAuthEQuestionsQuestionIdRoute: typeof NavbarLayoutAuthEQuestionsQuestionIdRoute
  NavbarLayoutAuthEQuestionsIndexRoute: typeof NavbarLayoutAuthEQuestionsIndexRoute
}

const NavbarLayoutAuthEQuestionsRouteChildren: NavbarLayoutAuthEQuestionsRouteChildren =
  {
    NavbarLayoutAuthEQuestionsQuestionIdRoute:
      NavbarLayoutAuthEQuestionsQuestionIdRoute,
    NavbarLayoutAuthEQuestionsIndexRoute: NavbarLayoutAuthEQuestionsIndexRoute,
  }

const NavbarLayoutAuthEQuestionsRouteWithChildren =
  NavbarLayoutAuthEQuestionsRoute._addFileChildren(
    NavbarLayoutAuthEQuestionsRouteChildren,
  )

interface NavbarLayoutAuthERouteChildren {
  NavbarLayoutAuthEGamesRoute: typeof NavbarLayoutAuthEGamesRouteWithChildren
  NavbarLayoutAuthEQuestionsRoute: typeof NavbarLayoutAuthEQuestionsRouteWithChildren
  NavbarLayoutAuthEIndexRoute: typeof NavbarLayoutAuthEIndexRoute
}

const NavbarLayoutAuthERouteChildren: NavbarLayoutAuthERouteChildren = {
  NavbarLayoutAuthEGamesRoute: NavbarLayoutAuthEGamesRouteWithChildren,
  NavbarLayoutAuthEQuestionsRoute: NavbarLayoutAuthEQuestionsRouteWithChildren,
  NavbarLayoutAuthEIndexRoute: NavbarLayoutAuthEIndexRoute,
}

const NavbarLayoutAuthERouteWithChildren =
  NavbarLayoutAuthERoute._addFileChildren(NavbarLayoutAuthERouteChildren)

interface NavbarLayoutAuthRouteChildren {
  NavbarLayoutAuthERoute: typeof NavbarLayoutAuthERouteWithChildren
}

const NavbarLayoutAuthRouteChildren: NavbarLayoutAuthRouteChildren = {
  NavbarLayoutAuthERoute: NavbarLayoutAuthERouteWithChildren,
}

const NavbarLayoutAuthRouteWithChildren =
  NavbarLayoutAuthRoute._addFileChildren(NavbarLayoutAuthRouteChildren)

interface NavbarLayoutRouteChildren {
  NavbarLayoutAuthRoute: typeof NavbarLayoutAuthRouteWithChildren
  NavbarLayoutActiveRoute: typeof NavbarLayoutActiveRoute
  NavbarLayoutLoginRoute: typeof NavbarLayoutLoginRoute
  NavbarLayoutIndexRoute: typeof NavbarLayoutIndexRoute
}

const NavbarLayoutRouteChildren: NavbarLayoutRouteChildren = {
  NavbarLayoutAuthRoute: NavbarLayoutAuthRouteWithChildren,
  NavbarLayoutActiveRoute: NavbarLayoutActiveRoute,
  NavbarLayoutLoginRoute: NavbarLayoutLoginRoute,
  NavbarLayoutIndexRoute: NavbarLayoutIndexRoute,
}

const NavbarLayoutRouteWithChildren = NavbarLayoutRoute._addFileChildren(
  NavbarLayoutRouteChildren,
)

interface NavbarLayoutauthCRouteChildren {
  NavbarLayoutauthCGameInstanceIdRoute: typeof NavbarLayoutauthCGameInstanceIdRoute
  NavbarLayoutauthCIndexRoute: typeof NavbarLayoutauthCIndexRoute
}

const NavbarLayoutauthCRouteChildren: NavbarLayoutauthCRouteChildren = {
  NavbarLayoutauthCGameInstanceIdRoute: NavbarLayoutauthCGameInstanceIdRoute,
  NavbarLayoutauthCIndexRoute: NavbarLayoutauthCIndexRoute,
}

const NavbarLayoutauthCRouteWithChildren =
  NavbarLayoutauthCRoute._addFileChildren(NavbarLayoutauthCRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof NavbarLayoutAuthRouteWithChildren
  '/about': typeof AboutLazyRoute
  '/active': typeof NavbarLayoutActiveRoute
  '/login': typeof NavbarLayoutLoginRoute
  '/g/$gameInstanceId': typeof GGameInstanceIdRoute
  '/': typeof NavbarLayoutIndexRoute
  '/e': typeof NavbarLayoutAuthERouteWithChildren
  '/c': typeof NavbarLayoutauthCRouteWithChildren
  '/e/games': typeof NavbarLayoutAuthEGamesRouteWithChildren
  '/e/questions': typeof NavbarLayoutAuthEQuestionsRouteWithChildren
  '/c/$gameInstanceId': typeof NavbarLayoutauthCGameInstanceIdRoute
  '/e/': typeof NavbarLayoutAuthEIndexRoute
  '/c/': typeof NavbarLayoutauthCIndexRoute
  '/e/games/$gameId': typeof NavbarLayoutAuthEGamesGameIdRoute
  '/e/questions/$questionId': typeof NavbarLayoutAuthEQuestionsQuestionIdRoute
  '/e/games/': typeof NavbarLayoutAuthEGamesIndexRoute
  '/e/questions/': typeof NavbarLayoutAuthEQuestionsIndexRoute
}

export interface FileRoutesByTo {
  '/about': typeof AboutLazyRoute
  '': typeof NavbarLayoutAuthRouteWithChildren
  '/active': typeof NavbarLayoutActiveRoute
  '/login': typeof NavbarLayoutLoginRoute
  '/g/$gameInstanceId': typeof GGameInstanceIdRoute
  '/': typeof NavbarLayoutIndexRoute
  '/c/$gameInstanceId': typeof NavbarLayoutauthCGameInstanceIdRoute
  '/e': typeof NavbarLayoutAuthEIndexRoute
  '/c': typeof NavbarLayoutauthCIndexRoute
  '/e/games/$gameId': typeof NavbarLayoutAuthEGamesGameIdRoute
  '/e/questions/$questionId': typeof NavbarLayoutAuthEQuestionsQuestionIdRoute
  '/e/games': typeof NavbarLayoutAuthEGamesIndexRoute
  '/e/questions': typeof NavbarLayoutAuthEQuestionsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_navbar-layout': typeof NavbarLayoutRouteWithChildren
  '/about': typeof AboutLazyRoute
  '/_navbar-layout/_auth': typeof NavbarLayoutAuthRouteWithChildren
  '/_navbar-layout/active': typeof NavbarLayoutActiveRoute
  '/_navbar-layout/login': typeof NavbarLayoutLoginRoute
  '/g/$gameInstanceId': typeof GGameInstanceIdRoute
  '/_navbar-layout/': typeof NavbarLayoutIndexRoute
  '/_navbar-layout/_auth/e': typeof NavbarLayoutAuthERouteWithChildren
  '/_navbar-layout/_auth/c': typeof NavbarLayoutauthCRouteWithChildren
  '/_navbar-layout/_auth/e/games': typeof NavbarLayoutAuthEGamesRouteWithChildren
  '/_navbar-layout/_auth/e/questions': typeof NavbarLayoutAuthEQuestionsRouteWithChildren
  '/_navbar-layout/_auth/c/$gameInstanceId': typeof NavbarLayoutauthCGameInstanceIdRoute
  '/_navbar-layout/_auth/e/': typeof NavbarLayoutAuthEIndexRoute
  '/_navbar-layout/_auth/c/': typeof NavbarLayoutauthCIndexRoute
  '/_navbar-layout/_auth/e/games/$gameId': typeof NavbarLayoutAuthEGamesGameIdRoute
  '/_navbar-layout/_auth/e/questions/$questionId': typeof NavbarLayoutAuthEQuestionsQuestionIdRoute
  '/_navbar-layout/_auth/e/games/': typeof NavbarLayoutAuthEGamesIndexRoute
  '/_navbar-layout/_auth/e/questions/': typeof NavbarLayoutAuthEQuestionsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/about'
    | '/active'
    | '/login'
    | '/g/$gameInstanceId'
    | '/'
    | '/e'
    | '/c'
    | '/e/games'
    | '/e/questions'
    | '/c/$gameInstanceId'
    | '/e/'
    | '/c/'
    | '/e/games/$gameId'
    | '/e/questions/$questionId'
    | '/e/games/'
    | '/e/questions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | ''
    | '/active'
    | '/login'
    | '/g/$gameInstanceId'
    | '/'
    | '/c/$gameInstanceId'
    | '/e'
    | '/c'
    | '/e/games/$gameId'
    | '/e/questions/$questionId'
    | '/e/games'
    | '/e/questions'
  id:
    | '__root__'
    | '/_navbar-layout'
    | '/about'
    | '/_navbar-layout/_auth'
    | '/_navbar-layout/active'
    | '/_navbar-layout/login'
    | '/g/$gameInstanceId'
    | '/_navbar-layout/'
    | '/_navbar-layout/_auth/e'
    | '/_navbar-layout/_auth/c'
    | '/_navbar-layout/_auth/e/games'
    | '/_navbar-layout/_auth/e/questions'
    | '/_navbar-layout/_auth/c/$gameInstanceId'
    | '/_navbar-layout/_auth/e/'
    | '/_navbar-layout/_auth/c/'
    | '/_navbar-layout/_auth/e/games/$gameId'
    | '/_navbar-layout/_auth/e/questions/$questionId'
    | '/_navbar-layout/_auth/e/games/'
    | '/_navbar-layout/_auth/e/questions/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  NavbarLayoutRoute: typeof NavbarLayoutRouteWithChildren
  AboutLazyRoute: typeof AboutLazyRoute
  GGameInstanceIdRoute: typeof GGameInstanceIdRoute
  NavbarLayoutauthCRoute: typeof NavbarLayoutauthCRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  NavbarLayoutRoute: NavbarLayoutRouteWithChildren,
  AboutLazyRoute: AboutLazyRoute,
  GGameInstanceIdRoute: GGameInstanceIdRoute,
  NavbarLayoutauthCRoute: NavbarLayoutauthCRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_navbar-layout",
        "/about",
        "/g/$gameInstanceId",
        "/_navbar-layout/_auth/c"
      ]
    },
    "/_navbar-layout": {
      "filePath": "_navbar-layout.tsx",
      "children": [
        "/_navbar-layout/_auth",
        "/_navbar-layout/active",
        "/_navbar-layout/login",
        "/_navbar-layout/"
      ]
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/_navbar-layout/_auth": {
      "filePath": "_navbar-layout._auth.tsx",
      "parent": "/_navbar-layout",
      "children": [
        "/_navbar-layout/_auth/e"
      ]
    },
    "/_navbar-layout/active": {
      "filePath": "_navbar-layout.active.tsx",
      "parent": "/_navbar-layout"
    },
    "/_navbar-layout/login": {
      "filePath": "_navbar-layout.login.tsx",
      "parent": "/_navbar-layout"
    },
    "/g/$gameInstanceId": {
      "filePath": "g.$gameInstanceId.tsx"
    },
    "/_navbar-layout/": {
      "filePath": "_navbar-layout.index.tsx",
      "parent": "/_navbar-layout"
    },
    "/_navbar-layout/_auth/e": {
      "filePath": "_navbar-layout._auth.e.tsx",
      "parent": "/_navbar-layout/_auth",
      "children": [
        "/_navbar-layout/_auth/e/games",
        "/_navbar-layout/_auth/e/questions",
        "/_navbar-layout/_auth/e/"
      ]
    },
    "/_navbar-layout/_auth/c": {
      "filePath": "_navbar-layout_._auth.c.tsx",
      "children": [
        "/_navbar-layout/_auth/c/$gameInstanceId",
        "/_navbar-layout/_auth/c/"
      ]
    },
    "/_navbar-layout/_auth/e/games": {
      "filePath": "_navbar-layout._auth.e.games.tsx",
      "parent": "/_navbar-layout/_auth/e",
      "children": [
        "/_navbar-layout/_auth/e/games/$gameId",
        "/_navbar-layout/_auth/e/games/"
      ]
    },
    "/_navbar-layout/_auth/e/questions": {
      "filePath": "_navbar-layout._auth.e.questions.tsx",
      "parent": "/_navbar-layout/_auth/e",
      "children": [
        "/_navbar-layout/_auth/e/questions/$questionId",
        "/_navbar-layout/_auth/e/questions/"
      ]
    },
    "/_navbar-layout/_auth/c/$gameInstanceId": {
      "filePath": "_navbar-layout_._auth.c.$gameInstanceId.tsx",
      "parent": "/_navbar-layout/_auth/c"
    },
    "/_navbar-layout/_auth/e/": {
      "filePath": "_navbar-layout._auth.e.index.tsx",
      "parent": "/_navbar-layout/_auth/e"
    },
    "/_navbar-layout/_auth/c/": {
      "filePath": "_navbar-layout_._auth.c.index.tsx",
      "parent": "/_navbar-layout/_auth/c"
    },
    "/_navbar-layout/_auth/e/games/$gameId": {
      "filePath": "_navbar-layout._auth.e.games.$gameId.tsx",
      "parent": "/_navbar-layout/_auth/e/games"
    },
    "/_navbar-layout/_auth/e/questions/$questionId": {
      "filePath": "_navbar-layout._auth.e.questions.$questionId.tsx",
      "parent": "/_navbar-layout/_auth/e/questions"
    },
    "/_navbar-layout/_auth/e/games/": {
      "filePath": "_navbar-layout._auth.e.games.index.tsx",
      "parent": "/_navbar-layout/_auth/e/games"
    },
    "/_navbar-layout/_auth/e/questions/": {
      "filePath": "_navbar-layout._auth.e.questions.index.tsx",
      "parent": "/_navbar-layout/_auth/e/questions"
    }
  }
}
ROUTE_MANIFEST_END */
