


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE EXTENSION IF NOT EXISTS "pg_net" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgsodium";






COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";





SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."game_events" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "instanceid" "uuid" NOT NULL,
    "eventid" smallint NOT NULL,
    "questionid" "uuid",
    "answerid" "uuid",
    "team" smallint,
    "points" integer,
    "userid" "uuid" DEFAULT "auth"."uid"()
);


ALTER TABLE "public"."game_events" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."game_instance" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "gameid" "uuid" NOT NULL,
    "userid" "uuid" DEFAULT "auth"."uid"() NOT NULL,
    "finished" timestamp without time zone,
    "team_left" "text",
    "team_right" "text",
    "join_code" "text",
    "join_code_expires" timestamp without time zone,
    "left_score" integer DEFAULT 0 NOT NULL,
    "right_score" integer DEFAULT 0 NOT NULL,
    "round_score" integer DEFAULT 0 NOT NULL,
    "answers" json DEFAULT '{}'::json NOT NULL,
    "question_text" "text" DEFAULT '""'::"text" NOT NULL,
    "confetti_mode" "text" DEFAULT 'disabled'::"text" NOT NULL,
    "strikes" smallint DEFAULT '0'::smallint NOT NULL,
    "current_question_id" "text",
    "completed_question_ids" "uuid"[] DEFAULT '{}'::"uuid"[] NOT NULL
);


ALTER TABLE "public"."game_instance" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."games" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text" DEFAULT ''::"text" NOT NULL,
    "userid" "uuid" DEFAULT "auth"."uid"() NOT NULL
);


ALTER TABLE "public"."games" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."active_games" WITH ("security_invoker"='true') AS
 SELECT "game_instance"."id",
    "game_instance"."created_at",
    "games"."name",
    "game_instance"."userid"
   FROM ("public"."game_instance"
     JOIN "public"."games" ON (("game_instance"."gameid" = "games"."id")))
  WHERE ("game_instance"."id" IN ( SELECT DISTINCT ON ("game_events"."instanceid") "game_events"."instanceid"
           FROM "public"."game_events"));


ALTER VIEW "public"."active_games" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."answers" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "question_id" "uuid" NOT NULL,
    "answer" "text" DEFAULT ''::"text" NOT NULL,
    "score" integer DEFAULT 0 NOT NULL,
    "user_id" "uuid" DEFAULT "auth"."uid"() NOT NULL
);


ALTER TABLE "public"."answers" OWNER TO "postgres";


ALTER TABLE "public"."game_events" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."game_events_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."game_questions" (
    "gameid" "uuid" NOT NULL,
    "questionid" "uuid" NOT NULL,
    "userid" "uuid" DEFAULT "auth"."uid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "position" "text" NOT NULL
);


ALTER TABLE "public"."game_questions" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."profiles" (
    "id" "uuid" NOT NULL,
    "first_name" "text",
    "last_name" "text",
    "display_name" "text"
);


ALTER TABLE "public"."profiles" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."questions" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "user_id" "uuid" DEFAULT "auth"."uid"() NOT NULL,
    "question" "text" DEFAULT ''::"text" NOT NULL
);


ALTER TABLE "public"."questions" OWNER TO "postgres";


ALTER TABLE ONLY "public"."answers"
    ADD CONSTRAINT "answers_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."game_events"
    ADD CONSTRAINT "game_events_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."game_instance"
    ADD CONSTRAINT "game_instance_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."game_questions"
    ADD CONSTRAINT "game_questions_pkey" PRIMARY KEY ("gameid", "questionid");



ALTER TABLE ONLY "public"."games"
    ADD CONSTRAINT "games_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."questions"
    ADD CONSTRAINT "questions_pkey" PRIMARY KEY ("id");



CREATE INDEX "answers_question_id_idx" ON "public"."answers" USING "btree" ("question_id");



CREATE INDEX "answers_user_id_idx" ON "public"."answers" USING "btree" ("user_id");



CREATE INDEX "game_events_instanceid_idx" ON "public"."game_events" USING "btree" ("instanceid");



CREATE INDEX "game_instance_finished_idx" ON "public"."game_instance" USING "btree" ("finished");



CREATE INDEX "game_instance_game_idx" ON "public"."game_instance" USING "btree" ("gameid");



CREATE INDEX "game_instance_userid_idx" ON "public"."game_instance" USING "btree" ("userid");



ALTER TABLE ONLY "public"."answers"
    ADD CONSTRAINT "answers_question_id_fkey" FOREIGN KEY ("question_id") REFERENCES "public"."questions"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."answers"
    ADD CONSTRAINT "answers_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."game_events"
    ADD CONSTRAINT "game_events_answerid_fkey" FOREIGN KEY ("answerid") REFERENCES "public"."answers"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."game_events"
    ADD CONSTRAINT "game_events_instanceid_fkey" FOREIGN KEY ("instanceid") REFERENCES "public"."game_instance"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."game_events"
    ADD CONSTRAINT "game_events_questionid_fkey" FOREIGN KEY ("questionid") REFERENCES "public"."questions"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."game_instance"
    ADD CONSTRAINT "game_instance_game_fkey" FOREIGN KEY ("gameid") REFERENCES "public"."games"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."game_instance"
    ADD CONSTRAINT "game_instance_userid_fkey" FOREIGN KEY ("userid") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."game_questions"
    ADD CONSTRAINT "game_questions_gameid_fkey" FOREIGN KEY ("gameid") REFERENCES "public"."games"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."game_questions"
    ADD CONSTRAINT "game_questions_questionid_fkey" FOREIGN KEY ("questionid") REFERENCES "public"."questions"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."game_questions"
    ADD CONSTRAINT "game_questions_userid_fkey" FOREIGN KEY ("userid") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."games"
    ADD CONSTRAINT "games_userid_fkey" FOREIGN KEY ("userid") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."questions"
    ADD CONSTRAINT "questions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE "public"."answers" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "authenticated can insert" ON "public"."game_events" FOR INSERT TO "authenticated" WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "userid"));



CREATE POLICY "authenticated users can insert" ON "public"."game_questions" FOR INSERT TO "authenticated" WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "userid"));



CREATE POLICY "authenticated users insert" ON "public"."questions" FOR INSERT TO "authenticated" WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "user_id"));



CREATE POLICY "check they are inserting for themselves" ON "public"."games" FOR INSERT TO "authenticated" WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "userid"));



CREATE POLICY "check uid is their own and user is authenticated" ON "public"."answers" FOR INSERT TO "authenticated" WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "user_id"));



CREATE POLICY "delete own answers" ON "public"."answers" FOR DELETE TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "user_id"));



CREATE POLICY "delete own events" ON "public"."game_events" FOR DELETE TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "userid"));



CREATE POLICY "delete own game instances" ON "public"."game_instance" FOR DELETE TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "userid"));



CREATE POLICY "delete own games" ON "public"."games" FOR DELETE TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "userid"));



CREATE POLICY "delete own questions" ON "public"."questions" FOR DELETE TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "user_id"));



CREATE POLICY "delete policy" ON "public"."game_questions" FOR DELETE TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "userid"));



ALTER TABLE "public"."game_events" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."game_instance" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."game_questions" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."games" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "insert own" ON "public"."game_instance" FOR INSERT TO "authenticated" WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "userid"));



ALTER TABLE "public"."profiles" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."questions" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "select own" ON "public"."game_instance" FOR SELECT TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "userid"));



CREATE POLICY "select own" ON "public"."game_questions" FOR SELECT TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "userid"));



CREATE POLICY "select own" ON "public"."games" FOR SELECT TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "userid"));



CREATE POLICY "select own" ON "public"."questions" FOR SELECT TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "user_id"));



CREATE POLICY "select own answers" ON "public"."answers" FOR SELECT TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "user_id"));



CREATE POLICY "select own events" ON "public"."game_events" FOR SELECT TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "userid"));



CREATE POLICY "update own" ON "public"."game_instance" FOR UPDATE TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "userid")) WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "userid"));



CREATE POLICY "update own answers" ON "public"."answers" FOR UPDATE TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "user_id")) WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "user_id"));



CREATE POLICY "update own games" ON "public"."games" FOR UPDATE TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "userid")) WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "userid"));



CREATE POLICY "update own questions" ON "public"."questions" FOR UPDATE TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "user_id")) WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "user_id"));



CREATE POLICY "update policy" ON "public"."game_questions" FOR UPDATE TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "userid")) WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "userid"));





ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."game_events";






GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";






























































































































































































































GRANT ALL ON TABLE "public"."game_events" TO "anon";
GRANT ALL ON TABLE "public"."game_events" TO "authenticated";
GRANT ALL ON TABLE "public"."game_events" TO "service_role";



GRANT ALL ON TABLE "public"."game_instance" TO "anon";
GRANT ALL ON TABLE "public"."game_instance" TO "authenticated";
GRANT ALL ON TABLE "public"."game_instance" TO "service_role";



GRANT ALL ON TABLE "public"."games" TO "anon";
GRANT ALL ON TABLE "public"."games" TO "authenticated";
GRANT ALL ON TABLE "public"."games" TO "service_role";



GRANT ALL ON TABLE "public"."active_games" TO "anon";
GRANT ALL ON TABLE "public"."active_games" TO "authenticated";
GRANT ALL ON TABLE "public"."active_games" TO "service_role";



GRANT ALL ON TABLE "public"."answers" TO "anon";
GRANT ALL ON TABLE "public"."answers" TO "authenticated";
GRANT ALL ON TABLE "public"."answers" TO "service_role";



GRANT ALL ON SEQUENCE "public"."game_events_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."game_events_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."game_events_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."game_questions" TO "anon";
GRANT ALL ON TABLE "public"."game_questions" TO "authenticated";
GRANT ALL ON TABLE "public"."game_questions" TO "service_role";



GRANT ALL ON TABLE "public"."profiles" TO "anon";
GRANT ALL ON TABLE "public"."profiles" TO "authenticated";
GRANT ALL ON TABLE "public"."profiles" TO "service_role";



GRANT ALL ON TABLE "public"."questions" TO "anon";
GRANT ALL ON TABLE "public"."questions" TO "authenticated";
GRANT ALL ON TABLE "public"."questions" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































